events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Servir el Frontend de Angular
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # MS-1: Autenticación
        location /api/auth/ {
            proxy_pass http://ms-auth:8011/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # MS-2: Periodos
        location /api/periods/ {
            proxy_pass http://ms-periods:8012/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # MS-3: Académicos
        location /api/academics/ {
            proxy_pass http://ms-academics:8013/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # MS-4: Calificaciones
        location /api/grades/ {
            proxy_pass http://ms-grades:8014/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # MS-5: Attendance
        location /api/attendance/ {
            proxy_pass http://ms-attendance:8015/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # MS-6: Notifications
        location /api/notifications/ { 
            proxy_pass http://ms-notifications:8016/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # MS-7: Reports
        location /api/reports/ {
            proxy_pass http://ms-reports:8017/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

    }
}