# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: academics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'academics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61\x63\x61\x64\x65mics.proto\x12\ragm.academics\"&\n\x10MateriaIdRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\x03\"$\n\x0f\x41lumnoIdRequest\x12\x11\n\talumno_id\x18\x01 \x01(\x03\"&\n\x10\x44ocenteIdRequest\x12\x12\n\ndocente_id\x18\x01 \x01(\x03\"\x1b\n\x0bNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"=\n\x14\x41lumnoMateriaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\x03\x12\x12\n\nmateria_id\x18\x02 \x01(\x03\"(\n\tBoolReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x80\x01\n\nAlumnoInfo\x12\x11\n\talumno_id\x18\x01 \x01(\x03\x12\x11\n\tmatricula\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\r\n\x05nivel\x18\x06 \x01(\t\x12\x0e\n\x06\x61\x63tivo\x18\x07 \x01(\x08\"6\n\nAlumnoList\x12(\n\x05items\x18\x01 \x03(\x0b\x32\x19.agm.academics.AlumnoInfo\"f\n\x0b\x44ocenteInfo\x12\x12\n\ndocente_id\x18\x01 \x01(\x03\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x11\n\tubicacion\x18\x04 \x01(\t\x12\x11\n\textension\x18\x05 \x01(\t2\xa1\x03\n\x10\x41\x63\x61\x64\x65micsService\x12Q\n\x13GetAlumnosByMateria\x12\x1f.agm.academics.MateriaIdRequest\x1a\x19.agm.academics.AlumnoList\x12J\n\rGetAlumnoById\x12\x1e.agm.academics.AlumnoIdRequest\x1a\x19.agm.academics.AlumnoInfo\x12R\n\x11IsAlumnoEnMateria\x12#.agm.academics.AlumnoMateriaRequest\x1a\x18.agm.academics.BoolReply\x12M\n\x0eGetDocenteById\x12\x1f.agm.academics.DocenteIdRequest\x1a\x1a.agm.academics.DocenteInfo\x12K\n\x11\x46indDocenteByName\x12\x1a.agm.academics.NameRequest\x1a\x1a.agm.academics.DocenteInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'academics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATERIAIDREQUEST']._serialized_start=34
  _globals['_MATERIAIDREQUEST']._serialized_end=72
  _globals['_ALUMNOIDREQUEST']._serialized_start=74
  _globals['_ALUMNOIDREQUEST']._serialized_end=110
  _globals['_DOCENTEIDREQUEST']._serialized_start=112
  _globals['_DOCENTEIDREQUEST']._serialized_end=150
  _globals['_NAMEREQUEST']._serialized_start=152
  _globals['_NAMEREQUEST']._serialized_end=179
  _globals['_ALUMNOMATERIAREQUEST']._serialized_start=181
  _globals['_ALUMNOMATERIAREQUEST']._serialized_end=242
  _globals['_BOOLREPLY']._serialized_start=244
  _globals['_BOOLREPLY']._serialized_end=284
  _globals['_ALUMNOINFO']._serialized_start=287
  _globals['_ALUMNOINFO']._serialized_end=415
  _globals['_ALUMNOLIST']._serialized_start=417
  _globals['_ALUMNOLIST']._serialized_end=471
  _globals['_DOCENTEINFO']._serialized_start=473
  _globals['_DOCENTEINFO']._serialized_end=575
  _globals['_ACADEMICSSERVICE']._serialized_start=578
  _globals['_ACADEMICSSERVICE']._serialized_end=995
# @@protoc_insertion_point(module_scope)
