# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import academics_pb2 as academics__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in academics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AcademicsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAlumnosByMateria = channel.unary_unary(
                '/agm.academics.AcademicsService/GetAlumnosByMateria',
                request_serializer=academics__pb2.MateriaIdRequest.SerializeToString,
                response_deserializer=academics__pb2.AlumnoList.FromString,
                _registered_method=True)
        self.GetAlumnoById = channel.unary_unary(
                '/agm.academics.AcademicsService/GetAlumnoById',
                request_serializer=academics__pb2.AlumnoIdRequest.SerializeToString,
                response_deserializer=academics__pb2.AlumnoInfo.FromString,
                _registered_method=True)
        self.IsAlumnoEnMateria = channel.unary_unary(
                '/agm.academics.AcademicsService/IsAlumnoEnMateria',
                request_serializer=academics__pb2.AlumnoMateriaRequest.SerializeToString,
                response_deserializer=academics__pb2.BoolReply.FromString,
                _registered_method=True)
        self.GetDocenteById = channel.unary_unary(
                '/agm.academics.AcademicsService/GetDocenteById',
                request_serializer=academics__pb2.DocenteIdRequest.SerializeToString,
                response_deserializer=academics__pb2.DocenteInfo.FromString,
                _registered_method=True)
        self.FindDocenteByName = channel.unary_unary(
                '/agm.academics.AcademicsService/FindDocenteByName',
                request_serializer=academics__pb2.NameRequest.SerializeToString,
                response_deserializer=academics__pb2.DocenteInfo.FromString,
                _registered_method=True)


class AcademicsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAlumnosByMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlumnoById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsAlumnoEnMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocenteById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindDocenteByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AcademicsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAlumnosByMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlumnosByMateria,
                    request_deserializer=academics__pb2.MateriaIdRequest.FromString,
                    response_serializer=academics__pb2.AlumnoList.SerializeToString,
            ),
            'GetAlumnoById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlumnoById,
                    request_deserializer=academics__pb2.AlumnoIdRequest.FromString,
                    response_serializer=academics__pb2.AlumnoInfo.SerializeToString,
            ),
            'IsAlumnoEnMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.IsAlumnoEnMateria,
                    request_deserializer=academics__pb2.AlumnoMateriaRequest.FromString,
                    response_serializer=academics__pb2.BoolReply.SerializeToString,
            ),
            'GetDocenteById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocenteById,
                    request_deserializer=academics__pb2.DocenteIdRequest.FromString,
                    response_serializer=academics__pb2.DocenteInfo.SerializeToString,
            ),
            'FindDocenteByName': grpc.unary_unary_rpc_method_handler(
                    servicer.FindDocenteByName,
                    request_deserializer=academics__pb2.NameRequest.FromString,
                    response_serializer=academics__pb2.DocenteInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agm.academics.AcademicsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agm.academics.AcademicsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AcademicsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAlumnosByMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.academics.AcademicsService/GetAlumnosByMateria',
            academics__pb2.MateriaIdRequest.SerializeToString,
            academics__pb2.AlumnoList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlumnoById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.academics.AcademicsService/GetAlumnoById',
            academics__pb2.AlumnoIdRequest.SerializeToString,
            academics__pb2.AlumnoInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsAlumnoEnMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.academics.AcademicsService/IsAlumnoEnMateria',
            academics__pb2.AlumnoMateriaRequest.SerializeToString,
            academics__pb2.BoolReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocenteById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.academics.AcademicsService/GetDocenteById',
            academics__pb2.DocenteIdRequest.SerializeToString,
            academics__pb2.DocenteInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindDocenteByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.academics.AcademicsService/FindDocenteByName',
            academics__pb2.NameRequest.SerializeToString,
            academics__pb2.DocenteInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
