# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import attendance_pb2 as attendance__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in attendance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AttendanceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAsistenciaAlumno = channel.unary_unary(
                '/agm.attendance.AttendanceService/GetAsistenciaAlumno',
                request_serializer=attendance__pb2.AlumnoMateriaRequest.SerializeToString,
                response_deserializer=attendance__pb2.AsistenciaReply.FromString,
                _registered_method=True)
        self.GetEstadisticasAsistencia = channel.unary_unary(
                '/agm.attendance.AttendanceService/GetEstadisticasAsistencia',
                request_serializer=attendance__pb2.MateriaIdRequest.SerializeToString,
                response_deserializer=attendance__pb2.StatsReply.FromString,
                _registered_method=True)
        self.GetHistorialMateria = channel.unary_unary(
                '/agm.attendance.AttendanceService/GetHistorialMateria',
                request_serializer=attendance__pb2.MateriaIdRequest.SerializeToString,
                response_deserializer=attendance__pb2.MateriaAsistenciaReply.FromString,
                _registered_method=True)


class AttendanceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAsistenciaAlumno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEstadisticasAsistencia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistorialMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttendanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAsistenciaAlumno': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAsistenciaAlumno,
                    request_deserializer=attendance__pb2.AlumnoMateriaRequest.FromString,
                    response_serializer=attendance__pb2.AsistenciaReply.SerializeToString,
            ),
            'GetEstadisticasAsistencia': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEstadisticasAsistencia,
                    request_deserializer=attendance__pb2.MateriaIdRequest.FromString,
                    response_serializer=attendance__pb2.StatsReply.SerializeToString,
            ),
            'GetHistorialMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistorialMateria,
                    request_deserializer=attendance__pb2.MateriaIdRequest.FromString,
                    response_serializer=attendance__pb2.MateriaAsistenciaReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agm.attendance.AttendanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agm.attendance.AttendanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttendanceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAsistenciaAlumno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.attendance.AttendanceService/GetAsistenciaAlumno',
            attendance__pb2.AlumnoMateriaRequest.SerializeToString,
            attendance__pb2.AsistenciaReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEstadisticasAsistencia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.attendance.AttendanceService/GetEstadisticasAsistencia',
            attendance__pb2.MateriaIdRequest.SerializeToString,
            attendance__pb2.StatsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistorialMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.attendance.AttendanceService/GetHistorialMateria',
            attendance__pb2.MateriaIdRequest.SerializeToString,
            attendance__pb2.MateriaAsistenciaReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
