# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: attendance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'attendance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ttendance.proto\x12\x0e\x61gm.attendance\"&\n\x10MateriaIdRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\x03\"=\n\x14\x41lumnoMateriaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\x03\x12\x12\n\nmateria_id\x18\x02 \x01(\x03\"B\n\x0e\x41sistenciaItem\x12\x11\n\tsesion_id\x18\x01 \x01(\x03\x12\r\n\x05\x66\x65\x63ha\x18\x02 \x01(\t\x12\x0e\n\x06\x65stado\x18\x03 \x01(\t\"@\n\x0f\x41sistenciaReply\x12-\n\x05items\x18\x01 \x03(\x0b\x32\x1e.agm.attendance.AsistenciaItem\"_\n\nStatsReply\x12\x16\n\x0etotal_sesiones\x18\x01 \x01(\x03\x12\x13\n\x0b\x61sistencias\x18\x02 \x01(\x03\x12\x10\n\x08retardos\x18\x03 \x01(\x03\x12\x12\n\nporcentaje\x18\x04 \x01(\x01\"^\n\x15MateriaAsistenciaItem\x12\x12\n\nsession_id\x18\x01 \x01(\x03\x12\x12\n\nstudent_id\x18\x02 \x01(\x03\x12\r\n\x05\x66\x65\x63ha\x18\x03 \x01(\t\x12\x0e\n\x06\x65stado\x18\x04 \x01(\t\"N\n\x16MateriaAsistenciaReply\x12\x34\n\x05items\x18\x01 \x03(\x0b\x32%.agm.attendance.MateriaAsistenciaItem2\xad\x02\n\x11\x41ttendanceService\x12\\\n\x13GetAsistenciaAlumno\x12$.agm.attendance.AlumnoMateriaRequest\x1a\x1f.agm.attendance.AsistenciaReply\x12Y\n\x19GetEstadisticasAsistencia\x12 .agm.attendance.MateriaIdRequest\x1a\x1a.agm.attendance.StatsReply\x12_\n\x13GetHistorialMateria\x12 .agm.attendance.MateriaIdRequest\x1a&.agm.attendance.MateriaAsistenciaReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attendance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATERIAIDREQUEST']._serialized_start=36
  _globals['_MATERIAIDREQUEST']._serialized_end=74
  _globals['_ALUMNOMATERIAREQUEST']._serialized_start=76
  _globals['_ALUMNOMATERIAREQUEST']._serialized_end=137
  _globals['_ASISTENCIAITEM']._serialized_start=139
  _globals['_ASISTENCIAITEM']._serialized_end=205
  _globals['_ASISTENCIAREPLY']._serialized_start=207
  _globals['_ASISTENCIAREPLY']._serialized_end=271
  _globals['_STATSREPLY']._serialized_start=273
  _globals['_STATSREPLY']._serialized_end=368
  _globals['_MATERIAASISTENCIAITEM']._serialized_start=370
  _globals['_MATERIAASISTENCIAITEM']._serialized_end=464
  _globals['_MATERIAASISTENCIAREPLY']._serialized_start=466
  _globals['_MATERIAASISTENCIAREPLY']._serialized_end=544
  _globals['_ATTENDANCESERVICE']._serialized_start=547
  _globals['_ATTENDANCESERVICE']._serialized_end=848
# @@protoc_insertion_point(module_scope)
