# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grades.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grades.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgrades.proto\x12\nagm.grades\"&\n\x10MateriaIdRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\x03\"=\n\x14\x41lumnoMateriaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\x03\x12\x12\n\nmateria_id\x18\x02 \x01(\x03\"\x1b\n\nFloatReply\x12\r\n\x05value\x18\x01 \x01(\x01\"P\n\nStatsReply\x12\x15\n\rtotal_alumnos\x18\x01 \x01(\x03\x12\x17\n\x0fpromedio_grupal\x18\x02 \x01(\x01\x12\x12\n\naprobacion\x18\x03 \x01(\x01\"d\n\x0b\x41lumnoCalif\x12\x11\n\talumno_id\x18\x01 \x01(\x03\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x15\n\rpromedio_real\x18\x03 \x01(\x01\x12\x1b\n\x13promedio_redondeado\x18\x04 \x01(\x05\":\n\x10\x43oncentradoReply\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.agm.grades.AlumnoCalif2\xfc\x01\n\rGradesService\x12L\n\x0eGetConcentrado\x12\x1c.agm.grades.MateriaIdRequest\x1a\x1c.agm.grades.ConcentradoReply\x12M\n\x11GetPromedioAlumno\x12 .agm.grades.AlumnoMateriaRequest\x1a\x16.agm.grades.FloatReply\x12N\n\x16GetEstadisticasMateria\x12\x1c.agm.grades.MateriaIdRequest\x1a\x16.agm.grades.StatsReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grades_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATERIAIDREQUEST']._serialized_start=28
  _globals['_MATERIAIDREQUEST']._serialized_end=66
  _globals['_ALUMNOMATERIAREQUEST']._serialized_start=68
  _globals['_ALUMNOMATERIAREQUEST']._serialized_end=129
  _globals['_FLOATREPLY']._serialized_start=131
  _globals['_FLOATREPLY']._serialized_end=158
  _globals['_STATSREPLY']._serialized_start=160
  _globals['_STATSREPLY']._serialized_end=240
  _globals['_ALUMNOCALIF']._serialized_start=242
  _globals['_ALUMNOCALIF']._serialized_end=342
  _globals['_CONCENTRADOREPLY']._serialized_start=344
  _globals['_CONCENTRADOREPLY']._serialized_end=402
  _globals['_GRADESSERVICE']._serialized_start=405
  _globals['_GRADESSERVICE']._serialized_end=657
# @@protoc_insertion_point(module_scope)
