# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grades_pb2 as grades__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grades_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GradesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConcentrado = channel.unary_unary(
                '/agm.grades.GradesService/GetConcentrado',
                request_serializer=grades__pb2.MateriaIdRequest.SerializeToString,
                response_deserializer=grades__pb2.ConcentradoReply.FromString,
                _registered_method=True)
        self.GetPromedioAlumno = channel.unary_unary(
                '/agm.grades.GradesService/GetPromedioAlumno',
                request_serializer=grades__pb2.AlumnoMateriaRequest.SerializeToString,
                response_deserializer=grades__pb2.FloatReply.FromString,
                _registered_method=True)
        self.GetEstadisticasMateria = channel.unary_unary(
                '/agm.grades.GradesService/GetEstadisticasMateria',
                request_serializer=grades__pb2.MateriaIdRequest.SerializeToString,
                response_deserializer=grades__pb2.StatsReply.FromString,
                _registered_method=True)


class GradesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetConcentrado(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPromedioAlumno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEstadisticasMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GradesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConcentrado': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConcentrado,
                    request_deserializer=grades__pb2.MateriaIdRequest.FromString,
                    response_serializer=grades__pb2.ConcentradoReply.SerializeToString,
            ),
            'GetPromedioAlumno': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPromedioAlumno,
                    request_deserializer=grades__pb2.AlumnoMateriaRequest.FromString,
                    response_serializer=grades__pb2.FloatReply.SerializeToString,
            ),
            'GetEstadisticasMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEstadisticasMateria,
                    request_deserializer=grades__pb2.MateriaIdRequest.FromString,
                    response_serializer=grades__pb2.StatsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agm.grades.GradesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agm.grades.GradesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GradesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetConcentrado(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.grades.GradesService/GetConcentrado',
            grades__pb2.MateriaIdRequest.SerializeToString,
            grades__pb2.ConcentradoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPromedioAlumno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.grades.GradesService/GetPromedioAlumno',
            grades__pb2.AlumnoMateriaRequest.SerializeToString,
            grades__pb2.FloatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEstadisticasMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.grades.GradesService/GetEstadisticasMateria',
            grades__pb2.MateriaIdRequest.SerializeToString,
            grades__pb2.StatsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
