# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import notifications_pb2 as notifications__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in notifications_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotificationsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendBienvenida = channel.unary_unary(
                '/agm.notifications.NotificationsService/SendBienvenida',
                request_serializer=notifications__pb2.BienvenidaRequest.SerializeToString,
                response_deserializer=notifications__pb2.BoolReply.FromString,
                _registered_method=True)
        self.SendBajaNotif = channel.unary_unary(
                '/agm.notifications.NotificationsService/SendBajaNotif',
                request_serializer=notifications__pb2.BajaRequest.SerializeToString,
                response_deserializer=notifications__pb2.BoolReply.FromString,
                _registered_method=True)
        self.SendCierreMateria = channel.unary_unary(
                '/agm.notifications.NotificationsService/SendCierreMateria',
                request_serializer=notifications__pb2.CierreMateriaRequest.SerializeToString,
                response_deserializer=notifications__pb2.BoolReply.FromString,
                _registered_method=True)
        self.SendResetPassword = channel.unary_unary(
                '/agm.notifications.NotificationsService/SendResetPassword',
                request_serializer=notifications__pb2.ResetPasswordRequest.SerializeToString,
                response_deserializer=notifications__pb2.BoolReply.FromString,
                _registered_method=True)


class NotificationsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendBienvenida(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBajaNotif(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCierreMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendResetPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendBienvenida': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBienvenida,
                    request_deserializer=notifications__pb2.BienvenidaRequest.FromString,
                    response_serializer=notifications__pb2.BoolReply.SerializeToString,
            ),
            'SendBajaNotif': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBajaNotif,
                    request_deserializer=notifications__pb2.BajaRequest.FromString,
                    response_serializer=notifications__pb2.BoolReply.SerializeToString,
            ),
            'SendCierreMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCierreMateria,
                    request_deserializer=notifications__pb2.CierreMateriaRequest.FromString,
                    response_serializer=notifications__pb2.BoolReply.SerializeToString,
            ),
            'SendResetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.SendResetPassword,
                    request_deserializer=notifications__pb2.ResetPasswordRequest.FromString,
                    response_serializer=notifications__pb2.BoolReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agm.notifications.NotificationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agm.notifications.NotificationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendBienvenida(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.notifications.NotificationsService/SendBienvenida',
            notifications__pb2.BienvenidaRequest.SerializeToString,
            notifications__pb2.BoolReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendBajaNotif(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.notifications.NotificationsService/SendBajaNotif',
            notifications__pb2.BajaRequest.SerializeToString,
            notifications__pb2.BoolReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCierreMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.notifications.NotificationsService/SendCierreMateria',
            notifications__pb2.CierreMateriaRequest.SerializeToString,
            notifications__pb2.BoolReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendResetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.notifications.NotificationsService/SendResetPassword',
            notifications__pb2.ResetPasswordRequest.SerializeToString,
            notifications__pb2.BoolReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
