# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: periods.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'periods.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rperiods.proto\x12\x0b\x61gm.periods\"\x07\n\x05\x45mpty\"&\n\x10MateriaIdRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\x03\"&\n\x10\x44ocenteIdRequest\x12\x12\n\ndocente_id\x18\x01 \x01(\x03\"&\n\x10PeriodoIdRequest\x12\x12\n\nperiodo_id\x18\x01 \x01(\x03\"\x81\x01\n\x0bPeriodoInfo\x12\x12\n\nperiodo_id\x18\x01 \x01(\x03\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x14\n\x0c\x66\x65\x63ha_inicio\x18\x03 \x01(\t\x12\x11\n\tfecha_fin\x18\x04 \x01(\t\x12\x15\n\rplan_estudios\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tivo\x18\x06 \x01(\x08\"\xcc\x01\n\x0bMateriaInfo\x12\x12\n\nmateria_id\x18\x01 \x01(\x03\x12\x12\n\nperiodo_id\x18\x02 \x01(\x03\x12\x12\n\ndocente_id\x18\x03 \x01(\x03\x12\x0b\n\x03nrc\x18\x04 \x01(\t\x12\r\n\x05\x63lave\x18\x05 \x01(\t\x12\x0e\n\x06nombre\x18\x06 \x01(\t\x12\x0f\n\x07seccion\x18\x07 \x01(\t\x12\x0f\n\x07\x64ocente\x18\x08 \x01(\t\x12\x14\n\x0chorario_json\x18\t \x01(\t\x12\r\n\x05salon\x18\n \x01(\t\x12\x0e\n\x06\x65stado\x18\x0b \x01(\t\"6\n\x0bMateriaList\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.agm.periods.MateriaInfo2\xbf\x02\n\x0ePeriodsService\x12I\n\x0eGetMateriaById\x12\x1d.agm.periods.MateriaIdRequest\x1a\x18.agm.periods.MateriaInfo\x12O\n\x14GetMateriasByDocente\x12\x1d.agm.periods.DocenteIdRequest\x1a\x18.agm.periods.MateriaList\x12O\n\x14GetMateriasByPeriodo\x12\x1d.agm.periods.PeriodoIdRequest\x1a\x18.agm.periods.MateriaList\x12@\n\x10GetPeriodoActivo\x12\x12.agm.periods.Empty\x1a\x18.agm.periods.PeriodoInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'periods_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_MATERIAIDREQUEST']._serialized_start=39
  _globals['_MATERIAIDREQUEST']._serialized_end=77
  _globals['_DOCENTEIDREQUEST']._serialized_start=79
  _globals['_DOCENTEIDREQUEST']._serialized_end=117
  _globals['_PERIODOIDREQUEST']._serialized_start=119
  _globals['_PERIODOIDREQUEST']._serialized_end=157
  _globals['_PERIODOINFO']._serialized_start=160
  _globals['_PERIODOINFO']._serialized_end=289
  _globals['_MATERIAINFO']._serialized_start=292
  _globals['_MATERIAINFO']._serialized_end=496
  _globals['_MATERIALIST']._serialized_start=498
  _globals['_MATERIALIST']._serialized_end=552
  _globals['_PERIODSSERVICE']._serialized_start=555
  _globals['_PERIODSSERVICE']._serialized_end=874
# @@protoc_insertion_point(module_scope)
