# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import periods_pb2 as periods__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in periods_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeriodsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMateriaById = channel.unary_unary(
                '/agm.periods.PeriodsService/GetMateriaById',
                request_serializer=periods__pb2.MateriaIdRequest.SerializeToString,
                response_deserializer=periods__pb2.MateriaInfo.FromString,
                _registered_method=True)
        self.GetMateriasByDocente = channel.unary_unary(
                '/agm.periods.PeriodsService/GetMateriasByDocente',
                request_serializer=periods__pb2.DocenteIdRequest.SerializeToString,
                response_deserializer=periods__pb2.MateriaList.FromString,
                _registered_method=True)
        self.GetMateriasByPeriodo = channel.unary_unary(
                '/agm.periods.PeriodsService/GetMateriasByPeriodo',
                request_serializer=periods__pb2.PeriodoIdRequest.SerializeToString,
                response_deserializer=periods__pb2.MateriaList.FromString,
                _registered_method=True)
        self.GetPeriodoActivo = channel.unary_unary(
                '/agm.periods.PeriodsService/GetPeriodoActivo',
                request_serializer=periods__pb2.Empty.SerializeToString,
                response_deserializer=periods__pb2.PeriodoInfo.FromString,
                _registered_method=True)


class PeriodsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMateriaById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMateriasByDocente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMateriasByPeriodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeriodoActivo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeriodsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMateriaById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMateriaById,
                    request_deserializer=periods__pb2.MateriaIdRequest.FromString,
                    response_serializer=periods__pb2.MateriaInfo.SerializeToString,
            ),
            'GetMateriasByDocente': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMateriasByDocente,
                    request_deserializer=periods__pb2.DocenteIdRequest.FromString,
                    response_serializer=periods__pb2.MateriaList.SerializeToString,
            ),
            'GetMateriasByPeriodo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMateriasByPeriodo,
                    request_deserializer=periods__pb2.PeriodoIdRequest.FromString,
                    response_serializer=periods__pb2.MateriaList.SerializeToString,
            ),
            'GetPeriodoActivo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeriodoActivo,
                    request_deserializer=periods__pb2.Empty.FromString,
                    response_serializer=periods__pb2.PeriodoInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agm.periods.PeriodsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agm.periods.PeriodsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeriodsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMateriaById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periods.PeriodsService/GetMateriaById',
            periods__pb2.MateriaIdRequest.SerializeToString,
            periods__pb2.MateriaInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMateriasByDocente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periods.PeriodsService/GetMateriasByDocente',
            periods__pb2.DocenteIdRequest.SerializeToString,
            periods__pb2.MateriaList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMateriasByPeriodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periods.PeriodsService/GetMateriasByPeriodo',
            periods__pb2.PeriodoIdRequest.SerializeToString,
            periods__pb2.MateriaList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeriodoActivo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.periods.PeriodsService/GetPeriodoActivo',
            periods__pb2.Empty.SerializeToString,
            periods__pb2.PeriodoInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
