# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reports.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reports.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreports.proto\x12\x0b\x61gm.reports\"P\n\x15GenerateReportRequest\x12\x13\n\x0breport_type\x18\x01 \x01(\t\x12\x12\n\nmateria_id\x18\x02 \x01(\x03\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\"A\n\tFileBytes\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x11\n\tmime_type\x18\x03 \x01(\t\"&\n\x10\x44ocenteIdRequest\x12\x12\n\ndocente_id\x18\x01 \x01(\x03\"C\n\x0cStatsPeriodo\x12\x0f\n\x07periodo\x18\x01 \x01(\t\x12\x10\n\x08materias\x18\x02 \x01(\x03\x12\x10\n\x08promedio\x18\x03 \x01(\x01\"=\n\x11StatsPeriodoReply\x12(\n\x05items\x18\x01 \x03(\x0b\x32\x19.agm.reports.StatsPeriodo2\xb4\x01\n\x0eReportsService\x12L\n\x0eGenerateReport\x12\".agm.reports.GenerateReportRequest\x1a\x16.agm.reports.FileBytes\x12T\n\x13GetHistorialDocente\x12\x1d.agm.reports.DocenteIdRequest\x1a\x1e.agm.reports.StatsPeriodoReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reports_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREPORTREQUEST']._serialized_start=30
  _globals['_GENERATEREPORTREQUEST']._serialized_end=110
  _globals['_FILEBYTES']._serialized_start=112
  _globals['_FILEBYTES']._serialized_end=177
  _globals['_DOCENTEIDREQUEST']._serialized_start=179
  _globals['_DOCENTEIDREQUEST']._serialized_end=217
  _globals['_STATSPERIODO']._serialized_start=219
  _globals['_STATSPERIODO']._serialized_end=286
  _globals['_STATSPERIODOREPLY']._serialized_start=288
  _globals['_STATSPERIODOREPLY']._serialized_end=349
  _globals['_REPORTSSERVICE']._serialized_start=352
  _globals['_REPORTSSERVICE']._serialized_end=532
# @@protoc_insertion_point(module_scope)
