# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reports_pb2 as reports__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in reports_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReportsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateReport = channel.unary_unary(
                '/agm.reports.ReportsService/GenerateReport',
                request_serializer=reports__pb2.GenerateReportRequest.SerializeToString,
                response_deserializer=reports__pb2.FileBytes.FromString,
                _registered_method=True)
        self.GetHistorialDocente = channel.unary_unary(
                '/agm.reports.ReportsService/GetHistorialDocente',
                request_serializer=reports__pb2.DocenteIdRequest.SerializeToString,
                response_deserializer=reports__pb2.StatsPeriodoReply.FromString,
                _registered_method=True)


class ReportsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistorialDocente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=reports__pb2.GenerateReportRequest.FromString,
                    response_serializer=reports__pb2.FileBytes.SerializeToString,
            ),
            'GetHistorialDocente': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistorialDocente,
                    request_deserializer=reports__pb2.DocenteIdRequest.FromString,
                    response_serializer=reports__pb2.StatsPeriodoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agm.reports.ReportsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agm.reports.ReportsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReportsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.reports.ReportsService/GenerateReport',
            reports__pb2.GenerateReportRequest.SerializeToString,
            reports__pb2.FileBytes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistorialDocente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agm.reports.ReportsService/GetHistorialDocente',
            reports__pb2.DocenteIdRequest.SerializeToString,
            reports__pb2.StatsPeriodoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
